import { mlModelManifestSchema, type MlModelManifest, type MlTaskType } from "./schemas.js";

type ManifestInput = Omit<MlModelManifest, "schemaVersion" | "backend" | "availability"> & {
  availability?: MlModelManifest["availability"];
};

function model(input: ManifestInput): MlModelManifest {
  return mlModelManifestSchema.parse({
    schemaVersion: 1,
    backend: "sklearn",
    availability: "available",
    ...input,
  });
}

const binary = ["binary_classification"] as const;
const multiclass = ["multiclass_classification"] as const;
const classification = ["binary_classification", "multiclass_classification"] as const;
const regression = ["regression"] as const;
const clustering = ["clustering"] as const;
const reduction = ["dimensionality_reduction"] as const;

export const mlModelCatalog: MlModelManifest[] = [
  model({
    id: "logistic-regression",
    label: "Logistic regression",
    tasks: [...classification],
    family: "linear",
    estimatorClass: "sklearn.linear_model.LogisticRegression",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: true,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { max_iter: 1000, solver: "lbfgs" },
    limitations: ["Linear decision boundary unless features are engineered.", "Coefficients require encoded feature inspection."],
  }),
  model({
    id: "knn-classifier",
    label: "k-nearest neighbors classifier",
    tasks: [...classification],
    family: "neighbors",
    estimatorClass: "sklearn.neighbors.KNeighborsClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { n_neighbors: 5 },
    limitations: ["Distance-sensitive; scaling is usually recommended.", "Can be slow on large row counts."],
  }),
  model({
    id: "svm-classifier",
    label: "support vector classifier",
    tasks: [...classification],
    family: "kernel",
    estimatorClass: "sklearn.svm.SVC",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { probability: true, kernel: "rbf" },
    limitations: ["Can be expensive on large datasets.", "Probability estimates add calibration overhead."],
  }),
  model({
    id: "decision-tree-classifier",
    label: "decision tree classifier",
    tasks: [...classification],
    family: "tree",
    estimatorClass: "sklearn.tree.DecisionTreeClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { min_samples_leaf: 2 },
    limitations: ["High variance without pruning or validation."],
  }),
  model({
    id: "random-forest-classifier",
    label: "random forest classifier",
    tasks: [...classification],
    family: "ensemble",
    estimatorClass: "sklearn.ensemble.RandomForestClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 100, n_jobs: 1 },
    limitations: ["Feature importance can be biased toward high-cardinality features."],
  }),
  model({
    id: "extra-trees-classifier",
    label: "extra trees classifier",
    tasks: [...classification],
    family: "ensemble",
    estimatorClass: "sklearn.ensemble.ExtraTreesClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 100, n_jobs: 1 },
    limitations: ["Randomized split thresholds can reduce interpretability."],
  }),
  model({
    id: "gradient-boosting-classifier",
    label: "gradient boosting classifier",
    tasks: [...classification],
    family: "boosting",
    estimatorClass: "sklearn.ensemble.GradientBoostingClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Tune cautiously to avoid overfitting."],
  }),
  model({
    id: "adaboost-classifier",
    label: "AdaBoost classifier",
    tasks: [...classification],
    family: "boosting",
    estimatorClass: "sklearn.ensemble.AdaBoostClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 50 },
    limitations: ["Sensitive to noisy labels and outliers."],
  }),
  model({
    id: "mlp-classifier",
    label: "multilayer perceptron classifier",
    tasks: [...classification],
    family: "neural_network",
    estimatorClass: "sklearn.neural_network.MLPClassifier",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { hidden_layer_sizes: [64], max_iter: 500, early_stopping: true },
    limitations: ["Requires scaling for most tabular data.", "Less interpretable than linear/tree baselines."],
  }),
  model({
    id: "xgboost-classifier",
    label: "XGBoost classifier",
    tasks: [...classification],
    family: "boosting",
    estimatorClass: "xgboost.XGBClassifier",
    availability: "optional_missing",
    requiredPackage: "xgboost",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { eval_metric: "logloss" },
    limitations: ["Optional dependency; install xgboost to enable."],
  }),
  model({
    id: "lightgbm-classifier",
    label: "LightGBM classifier",
    tasks: [...classification],
    family: "boosting",
    estimatorClass: "lightgbm.LGBMClassifier",
    availability: "optional_missing",
    requiredPackage: "lightgbm",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Optional dependency; install lightgbm to enable."],
  }),
  model({
    id: "catboost-classifier",
    label: "CatBoost classifier",
    tasks: [...classification],
    family: "boosting",
    estimatorClass: "catboost.CatBoostClassifier",
    availability: "optional_missing",
    requiredPackage: "catboost",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { verbose: false },
    limitations: ["Optional dependency; install catboost to enable."],
  }),
  model({
    id: "linear-regression",
    label: "linear regression",
    tasks: [...regression],
    family: "linear",
    estimatorClass: "sklearn.linear_model.LinearRegression",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: true,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Assumes linear conditional mean unless features are transformed."],
  }),
  model({
    id: "ridge-regression",
    label: "ridge regression",
    tasks: [...regression],
    family: "linear",
    estimatorClass: "sklearn.linear_model.Ridge",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: true,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { alpha: 1.0 },
    limitations: ["Coefficients are shrunk but not sparse."],
  }),
  model({
    id: "lasso-regression",
    label: "lasso regression",
    tasks: [...regression],
    family: "linear",
    estimatorClass: "sklearn.linear_model.Lasso",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: true,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { alpha: 0.01, max_iter: 5000 },
    limitations: ["Sparse coefficients are sensitive to feature scaling and alpha."],
  }),
  model({
    id: "elastic-net-regression",
    label: "elastic net regression",
    tasks: [...regression],
    family: "linear",
    estimatorClass: "sklearn.linear_model.ElasticNet",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: true,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { alpha: 0.01, l1_ratio: 0.5, max_iter: 5000 },
    limitations: ["Requires alpha/l1_ratio tuning for final inference."],
  }),
  model({
    id: "svr",
    label: "support vector regression",
    tasks: [...regression],
    family: "kernel",
    estimatorClass: "sklearn.svm.SVR",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Can be expensive on large datasets.", "Scaling is usually required."],
  }),
  model({
    id: "knn-regressor",
    label: "k-nearest neighbors regressor",
    tasks: [...regression],
    family: "neighbors",
    estimatorClass: "sklearn.neighbors.KNeighborsRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { n_neighbors: 5 },
    limitations: ["Distance-sensitive; scaling is usually recommended."],
  }),
  model({
    id: "decision-tree-regressor",
    label: "decision tree regressor",
    tasks: [...regression],
    family: "tree",
    estimatorClass: "sklearn.tree.DecisionTreeRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { min_samples_leaf: 2 },
    limitations: ["High variance without pruning or validation."],
  }),
  model({
    id: "random-forest-regressor",
    label: "random forest regressor",
    tasks: [...regression],
    family: "ensemble",
    estimatorClass: "sklearn.ensemble.RandomForestRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 100, n_jobs: 1 },
    limitations: ["Feature importance can be biased toward high-cardinality features."],
  }),
  model({
    id: "extra-trees-regressor",
    label: "extra trees regressor",
    tasks: [...regression],
    family: "ensemble",
    estimatorClass: "sklearn.ensemble.ExtraTreesRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 100, n_jobs: 1 },
    limitations: ["Randomized split thresholds can reduce interpretability."],
  }),
  model({
    id: "gradient-boosting-regressor",
    label: "gradient boosting regressor",
    tasks: [...regression],
    family: "boosting",
    estimatorClass: "sklearn.ensemble.GradientBoostingRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Tune cautiously to avoid overfitting."],
  }),
  model({
    id: "adaboost-regressor",
    label: "AdaBoost regressor",
    tasks: [...regression],
    family: "boosting",
    estimatorClass: "sklearn.ensemble.AdaBoostRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { n_estimators: 50 },
    limitations: ["Sensitive to noisy continuous targets."],
  }),
  model({
    id: "mlp-regressor",
    label: "multilayer perceptron regressor",
    tasks: [...regression],
    family: "neural_network",
    estimatorClass: "sklearn.neural_network.MLPRegressor",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: true,
    defaultParams: { hidden_layer_sizes: [64], max_iter: 500, early_stopping: true },
    limitations: ["Requires scaling for most tabular data.", "Less interpretable than linear/tree baselines."],
  }),
  model({
    id: "xgboost-regressor",
    label: "XGBoost regressor",
    tasks: [...regression],
    family: "boosting",
    estimatorClass: "xgboost.XGBRegressor",
    availability: "optional_missing",
    requiredPackage: "xgboost",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Optional dependency; install xgboost to enable."],
  }),
  model({
    id: "lightgbm-regressor",
    label: "LightGBM regressor",
    tasks: [...regression],
    family: "boosting",
    estimatorClass: "lightgbm.LGBMRegressor",
    availability: "optional_missing",
    requiredPackage: "lightgbm",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: {},
    limitations: ["Optional dependency; install lightgbm to enable."],
  }),
  model({
    id: "catboost-regressor",
    label: "CatBoost regressor",
    tasks: [...regression],
    family: "boosting",
    estimatorClass: "catboost.CatBoostRegressor",
    availability: "optional_missing",
    requiredPackage: "catboost",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: true,
    supportsPermutationImportance: true,
    defaultParams: { verbose: false },
    limitations: ["Optional dependency; install catboost to enable."],
  }),
  model({
    id: "k-means",
    label: "k-means clustering",
    tasks: [...clustering],
    family: "neighbors",
    estimatorClass: "sklearn.cluster.KMeans",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_clusters: 3, n_init: 10 },
    limitations: ["Requires a chosen cluster count.", "Assumes roughly spherical clusters."],
  }),
  model({
    id: "mini-batch-k-means",
    label: "mini-batch k-means clustering",
    tasks: [...clustering],
    family: "neighbors",
    estimatorClass: "sklearn.cluster.MiniBatchKMeans",
    supportsPredict: true,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_clusters: 3, n_init: 10 },
    limitations: ["Approximate k-means for larger datasets."],
  }),
  model({
    id: "agglomerative-clustering",
    label: "agglomerative clustering",
    tasks: [...clustering],
    family: "neighbors",
    estimatorClass: "sklearn.cluster.AgglomerativeClustering",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_clusters: 3 },
    limitations: ["No native predict for new observations."],
  }),
  model({
    id: "dbscan",
    label: "DBSCAN clustering",
    tasks: [...clustering],
    family: "neighbors",
    estimatorClass: "sklearn.cluster.DBSCAN",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { eps: 0.5, min_samples: 5 },
    limitations: ["Sensitive to eps/min_samples.", "Noise points receive cluster -1."],
  }),
  model({
    id: "gaussian-mixture",
    label: "Gaussian mixture model",
    tasks: [...clustering],
    family: "mixture",
    estimatorClass: "sklearn.mixture.GaussianMixture",
    supportsPredict: true,
    supportsPredictProba: true,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 3 },
    limitations: ["Requires component count and Gaussian assumptions."],
  }),
  model({
    id: "spectral-clustering",
    label: "spectral clustering",
    tasks: [...clustering],
    family: "neighbors",
    estimatorClass: "sklearn.cluster.SpectralClustering",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_clusters: 3, assign_labels: "kmeans" },
    limitations: ["Can be expensive; no native predict for new observations."],
  }),
  model({
    id: "pca",
    label: "principal component analysis",
    tasks: [...reduction],
    family: "decomposition",
    estimatorClass: "sklearn.decomposition.PCA",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 2 },
    limitations: ["Linear dimensionality reduction.", "Categorical encodings influence component geometry."],
  }),
  model({
    id: "truncated-svd",
    label: "truncated SVD",
    tasks: [...reduction],
    family: "decomposition",
    estimatorClass: "sklearn.decomposition.TruncatedSVD",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 2 },
    limitations: ["Useful for sparse/high-dimensional data; components are linear."],
  }),
  model({
    id: "nmf",
    label: "non-negative matrix factorization",
    tasks: [...reduction],
    family: "decomposition",
    estimatorClass: "sklearn.decomposition.NMF",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 2, init: "nndsvda", max_iter: 500 },
    limitations: ["Requires non-negative transformed features."],
  }),
  model({
    id: "tsne",
    label: "t-SNE",
    tasks: [...reduction],
    family: "manifold",
    estimatorClass: "sklearn.manifold.TSNE",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: false,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 2, perplexity: 30 },
    limitations: ["Visualization-oriented; no transform for new samples in sklearn.", "Perplexity must be smaller than row count."],
  }),
  model({
    id: "umap",
    label: "UMAP",
    tasks: [...reduction],
    family: "manifold",
    estimatorClass: "umap.UMAP",
    availability: "optional_missing",
    requiredPackage: "umap-learn",
    supportsPredict: false,
    supportsPredictProba: false,
    supportsEvaluation: true,
    supportsSerialization: true,
    supportsCoefficients: false,
    supportsFeatureImportance: false,
    supportsPermutationImportance: false,
    defaultParams: { n_components: 2 },
    limitations: ["Optional dependency; install umap-learn to enable."],
  }),
];

export function listMlModels(opts: { task?: MlTaskType; includeUnavailable?: boolean } = {}): MlModelManifest[] {
  return mlModelCatalog.filter(model => {
    if (opts.task && !model.tasks.includes(opts.task)) return false;
    if (!opts.includeUnavailable && model.availability !== "available") return false;
    return true;
  });
}

export function getMlModelManifest(modelId: string): MlModelManifest {
  const manifest = mlModelCatalog.find(model => model.id === modelId);
  if (!manifest) {
    const known = mlModelCatalog.map(model => model.id).join(", ");
    throw new Error(`Unknown ML model '${modelId}'. Known models: ${known}`);
  }
  return manifest;
}

export function assertMlModelCompatible(modelId: string, task: MlTaskType): MlModelManifest {
  const manifest = assertMlModelTaskCompatible(modelId, task);
  if (manifest.availability === "optional_missing") {
    throw new Error(`ML model '${modelId}' requires optional package '${manifest.requiredPackage ?? "unknown"}'. Install it in the selected Python environment to enable this adapter.`);
  }
  return manifest;
}

export function assertMlModelTaskCompatible(modelId: string, task: MlTaskType): MlModelManifest {
  const manifest = getMlModelManifest(modelId);
  if (!manifest.tasks.includes(task)) {
    throw new Error(`ML model '${modelId}' is not compatible with task '${task}'. Compatible tasks: ${manifest.tasks.join(", ")}`);
  }
  return manifest;
}

export function defaultPrimaryMetric(task: MlTaskType): { metric: string; direction: "maximize" | "minimize" } {
  switch (task) {
    case "binary_classification":
      return { metric: "auroc", direction: "maximize" };
    case "multiclass_classification":
      return { metric: "macro_f1", direction: "maximize" };
    case "regression":
      return { metric: "rmse", direction: "minimize" };
    case "clustering":
      return { metric: "silhouette", direction: "maximize" };
    case "dimensionality_reduction":
      return { metric: "explained_variance_ratio_sum", direction: "maximize" };
  }
}
