import type { StatsMethod } from "./schemas.js";

const analysisMethodToStatsMethod: Readonly<Record<string, StatsMethod>> = {
  "table-one-descriptive-summary": "descriptive",
  "two-sample-t-test": "t-test",
  "paired-t-test": "paired-t-test",
  "welch-t-test": "welch-t-test",
  "anova-one-way": "anova",
  "ancova": "ancova",
  "mann-whitney-u": "mann-whitney",
  "wilcoxon-signed-rank": "wilcoxon",
  "kruskal-wallis": "kruskal-wallis",
  "friedman-test": "friedman",
  "chi-square-independence": "chi-square",
  "fisher-exact-test": "fisher-exact",
  "mcnemar-test": "mcnemar",
  "cochran-q-test": "cochran-q",
  "cochran-armitage-trend": "cochran-armitage-trend",
  "pearson-correlation": "pearson",
  "spearman-correlation": "spearman",
  "kendall-correlation": "kendall",
  "partial-correlation": "partial-correlation",
  "multiple-linear-regression": "linear-regression",
  "robust-linear-regression": "robust-linear-regression",
  "binary-logistic-regression": "logistic-regression",
  "ordinal-logistic-regression": "ordinal-logistic-regression",
  "multinomial-logistic-regression": "multinomial-logistic-regression",
  "poisson-regression": "poisson-regression",
  "negative-binomial-regression": "negative-binomial-regression",
  "zero-inflated-poisson": "zero-inflated-poisson",
  "zero-inflated-negative-binomial": "zero-inflated-negative-binomial",
  "gamma-glm": "gamma-glm",
  "inverse-gaussian-glm": "inverse-gaussian-glm",
  "quantile-regression": "quantile-regression",
  "penalized-regression-elastic-net": "penalized-linear-regression",
  "kaplan-meier-log-rank": "kaplan-meier",
  "cox-proportional-hazards": "cox-proportional-hazards",
  "recurrent-event-cox-andersen-gill": "recurrent-event-cox",
  "fine-gray-competing-risks": "fine-gray",
  "linear-mixed-effects-model": "linear-mixed-model",
  "multilevel-logistic-model": "generalized-mixed-model",
  "generalized-estimating-equations": "gee",
  "repeated-measures-anova": "repeated-measures-anova",
  "difference-in-differences": "difference-in-differences",
  "interrupted-time-series": "interrupted-time-series",
  "regression-discontinuity": "regression-discontinuity",
  "tmle-doubly-robust": "doubly-robust-aipw",
  "multiple-imputation-mice": "multiple-imputation-mice",
  "model-diagnostics-linear-logistic": "model-diagnostics",
  "cohens-kappa-icc": "reliability-kappa",
  "cronbach-alpha-scale": "cronbach-alpha",
  "pca-dimensionality-reduction": "pca",
  "kmeans-clustering": "clustering-validation",
  "bland-altman": "bland-altman",
  "multiple-comparison-fdr": "multiple-comparison-correction",
  "power-sample-size": "power-sample-size",
  "diagnostic-accuracy-basic": "diagnostic-accuracy",
  "roc-auc-calibration": "prediction-evaluation",
  "propensity-score-matching": "propensity-score-matching",
  "propensity-score-weighting": "propensity-score-weighting",
  "cross-validation-bootstrap-validation": "prediction-evaluation",
};

export function statsRunMethodForAnalysisMethod(methodId: string): StatsMethod | null {
  return analysisMethodToStatsMethod[methodId] ?? null;
}

export function analysisMethodIdsWithStatsRunner(): string[] {
  return Object.keys(analysisMethodToStatsMethod);
}
