import { z } from "zod";

export const statsMethodSchema = z.enum([
  "descriptive",
  "t-test",
  "paired-t-test",
  "welch-t-test",
  "anova",
  "ancova",
  "mann-whitney",
  "wilcoxon",
  "kruskal-wallis",
  "friedman",
  "chi-square",
  "fisher-exact",
  "mcnemar",
  "cochran-armitage-trend",
  "pearson",
  "spearman",
  "kendall",
  "partial-correlation",
  "linear-regression",
  "robust-linear-regression",
  "logistic-regression",
  "ordinal-logistic-regression",
  "multinomial-logistic-regression",
  "poisson-regression",
  "negative-binomial-regression",
  "zero-inflated-poisson",
  "zero-inflated-negative-binomial",
  "gamma-glm",
  "inverse-gaussian-glm",
  "quantile-regression",
  "penalized-linear-regression",
  "penalized-logistic-regression",
  "kaplan-meier",
  "log-rank",
  "cox-proportional-hazards",
  "stratified-cox",
  "time-varying-cox",
  "fine-gray",
  "aalen-johansen-cif",
  "recurrent-event-rate",
  "linear-mixed-model",
  "generalized-mixed-model",
  "gee",
  "repeated-measures-anova",
  "overlap-weighting",
  "entropy-balancing",
  "doubly-robust-aipw",
  "difference-in-differences",
  "event-study-did",
  "interrupted-time-series",
  "regression-discontinuity",
  "instrumental-variables-2sls",
  "target-trial-emulation-spec",
  "unmeasured-confounding-sensitivity",
  "prediction-evaluation",
  "missingness-summary",
  "multiple-imputation-mice",
  "missingness-ipw",
  "complete-case-sensitivity",
  "mnar-sensitivity",
  "model-diagnostics",
  "reliability-kappa",
  "intraclass-correlation",
  "cronbach-alpha",
  "pca",
  "clustering-validation",
  "bland-altman",
  "multiple-comparison-correction",
  "power-sample-size",
  "diagnostic-accuracy",
  "propensity-score-matching",
  "propensity-score-weighting",
]);
export type StatsMethod = z.infer<typeof statsMethodSchema>;

export const statsRunRequestSchema = z.object({
  schemaVersion: z.literal(1),
  method: statsMethodSchema,
  dataPath: z.string().min(1),
  outcome: z.string().min(1).optional(),
  exposure: z.string().min(1).optional(),
  group: z.string().min(1).optional(),
  outcomeThreshold: z.number().optional(),
  exposureThreshold: z.number().optional(),
  variables: z.array(z.string().min(1)).default([]),
  covariates: z.array(z.string().min(1)).default([]),
  time: z.string().min(1).optional(),
  event: z.string().min(1).optional(),
  id: z.string().min(1).optional(),
  strata: z.string().min(1).optional(),
  cluster: z.string().min(1).optional(),
  period: z.string().min(1).optional(),
  post: z.string().min(1).optional(),
  runningVariable: z.string().min(1).optional(),
  cutoff: z.number().optional(),
  instrument: z.string().min(1).optional(),
  alphaPenalty: z.number().min(0).optional(),
  l1Ratio: z.number().min(0).max(1).optional(),
  weight: z.string().min(1).optional(),
  exactCovariates: z.array(z.string().min(1)).default([]),
  estimand: z.enum(["ATE", "ATT"]).default("ATT"),
  matchRatio: z.number().int().min(1).max(10).default(1),
  caliper: z.number().positive().max(10).optional(),
  replacement: z.boolean().default(false),
  trimThreshold: z.number().min(0).max(0.49).default(0.01),
  stabilizeWeights: z.boolean().default(true),
  surveyDesign: z.boolean().default(false),
  allowSurveyApproximation: z.boolean().default(false),
  methodSelectionPath: z.string().min(1).optional(),
  analysisSpecPath: z.string().min(1).optional(),
  outDir: z.string().min(1),
  alpha: z.number().min(0.0001).max(0.5).default(0.05),
  python: z.string().min(1).optional(),
});
export type StatsRunRequest = z.infer<typeof statsRunRequestSchema>;

export const statsArtifactSchema = z.object({
  kind: z.enum(["config", "method-contract", "preflight", "preflight-report", "summary", "table", "diagnostics", "model-diagnostics", "report", "qa", "balance", "propensity-scores", "propensity-overlap", "matched-pairs", "weights", "figure", "figure-manifest", "figure-qa", "imputed-data"]),
  path: z.string().min(1),
  sha256: z.string().optional(),
});
export type StatsArtifact = z.infer<typeof statsArtifactSchema>;

export const statsIssueSchema = z.object({
  severity: z.enum(["blocker", "warning", "note"]),
  code: z.string().min(1),
  message: z.string().min(1),
  evidenceRefs: z.array(z.string()).default([]),
});
export type StatsIssue = z.infer<typeof statsIssueSchema>;

export const statsResultPostureSchema = z.object({
  status: z.enum([
    "failed",
    "blocked_survey_required",
    "invalid_binding",
    "exploratory_survey_approximation",
    "exploratory_standard_table",
    "bound_standard_table",
    "causal_design_review_required",
  ]),
  label: z.string().min(1),
  interpretationBoundary: z.string().min(1),
  supports: z.array(z.string().min(1)),
  cannotSupport: z.array(z.string().min(1)),
  nextAction: z.string().min(1),
});
export type StatsResultPosture = z.infer<typeof statsResultPostureSchema>;

export const statsRunResultSchema = z.object({
  schemaVersion: z.literal(1),
  runId: z.string().min(1),
  method: statsMethodSchema,
  status: z.enum(["succeeded", "failed"]),
  rowCount: z.number().int().nonnegative(),
  completeCaseN: z.number().int().nonnegative(),
  variables: z.array(z.string()),
  binding: z.object({
    methodSelectionPath: z.string().nullable(),
    methodSelectionId: z.string().nullable(),
    methodId: z.string().nullable(),
    analysisSpecPath: z.string().nullable(),
    specHash: z.string().nullable(),
    status: z.enum(["unbound", "bound", "mismatch", "invalid"]),
  }),
  parameters: z.record(z.string(), z.unknown()),
  estimates: z.array(z.record(z.string(), z.unknown())),
  diagnostics: z.record(z.string(), z.unknown()),
  issues: z.array(statsIssueSchema),
  warnings: z.array(z.string()),
  errors: z.array(z.string()),
  resultPosture: statsResultPostureSchema.optional(),
  artifacts: z.array(statsArtifactSchema),
  outDir: z.string().min(1),
});
export type StatsRunResult = z.infer<typeof statsRunResultSchema>;
