import path from "node:path";
import type { SpecializationManifest } from "./schemas.js";

export function builtInResearchMethodsSpecialist(rootDir: string): SpecializationManifest {
  return {
    schemaVersion: 1,
    id: "research-methods-specialist",
    name: "Research Methods Specialist",
    version: "0.1.0",
    purpose: "Generate and evaluate research-analysis workflow variants.",
    domain: "medical-public-health-research",
    allowedCapabilities: ["research.question.design", "research.method.select", "research.analysis.plan", "research.qa.critique"],
    allowedTools: ["local-fixtures", "json-schema", "deterministic-rubric"],
    allowedActions: ["fs.read", "fs.write", "evaluate.fixture", "promote.artifact"],
    requiredInputs: ["research question", "dataset or fixture", "evaluation rubric"],
    expectedOutputs: ["workflow variant", "analysis plan", "evaluation result", "critique", "promotion decision"],
    workflowTemplates: [
      {
        id: "research-analysis-loop",
        description: "Question -> protocol -> method selection -> analysis plan -> QA critique -> promotion decision.",
        steps: ["clarify question", "select method", "declare artifacts", "run QA", "record decision"],
      },
    ],
    candidateGenerators: [
      { id: "baseline-conservative", strategy: "baseline", description: "Conservative workflow with explicit validation gates." },
      { id: "strict-methods", strategy: "strict", description: "Methods-first workflow that refuses unsupported inference." },
      { id: "creative-tail", strategy: "creative", description: "Alternative workflow that adds adversarial QA and sensitivity checks." },
      { id: "known-bad", strategy: "adversarial", description: "Deliberately flawed candidate used to prove rejection." },
    ],
    evaluators: [
      { id: "fixture-behavior", type: "fixture-test", description: "Runs candidate against deterministic specialization fixtures." },
      { id: "schema-output", type: "schema-validation", description: "Validates required output fields and artifacts." },
      { id: "baseline-delta", type: "baseline-comparison", description: "Compares candidate score with fixture baseline." },
      { id: "cost-budget", type: "cost-time-budget", description: "Blocks candidates exceeding declared local budget." },
      { id: "artifact-completeness", type: "artifact-completeness", description: "Requires candidate artifacts before promotion." },
      { id: "reproducibility", type: "reproducibility", description: "Hashes inputs, candidates, and artifacts." },
    ],
    critics: [
      { id: "methods-critic", type: "deterministic", rubricId: "research-methods-rubric" },
    ],
    repairPolicies: [
      { id: "add-missing-artifact", trigger: "missing required artifact", action: "Add declared output artifact and rerun evaluation.", maxAttempts: 1 },
      { id: "remove-overclaim", trigger: "overclaiming issue", action: "Downgrade causal/paper-ready claim to exploratory and rerun critique.", maxAttempts: 1 },
    ],
    baselineStrategies: [
      { id: "manual-baseline", description: "Human-authored conservative baseline workflow.", expectedMetric: 0.55 },
    ],
    promotionCriteria: {
      minScore: 0.74,
      minBaselineDelta: 0.05,
      requireCritiquePass: true,
      requireAllFixturesPass: false,
      maxCostUsd: 0,
      maxRiskFlags: 1,
    },
    artifactSchemas: [
      { kind: "workflow", requiredFields: ["steps", "validationGates", "outputs"] },
      { kind: "analysis-plan", requiredFields: ["method", "variables", "limitations"] },
      { kind: "qa-report", requiredFields: ["status", "issues", "recommendation"] },
    ],
    fixtures: [
      {
        id: "binary-classification-fixture",
        title: "Simple tabular binary classification problem",
        task: "Design a bounded workflow for binary classification with calibration and leakage checks.",
        expectedOutputs: ["workflow", "analysis-plan", "qa-report"],
        expectedKeywords: ["binary", "calibration", "leakage", "train/test", "artifact"],
        forbiddenKeywords: ["causal proof", "diagnostic certainty"],
        requiredArtifacts: ["workflow", "analysis-plan"],
        baselineMetric: 0.58,
        shouldReject: false,
        tags: ["ml", "classification"],
      },
      {
        id: "regression-fixture",
        title: "Simple regression problem",
        task: "Design a standard-table regression workflow with residual diagnostics and limitations.",
        expectedOutputs: ["workflow", "analysis-plan", "qa-report"],
        expectedKeywords: ["regression", "residual", "diagnostic", "limitations"],
        forbiddenKeywords: ["guaranteed causal"],
        requiredArtifacts: ["workflow", "analysis-plan"],
        baselineMetric: 0.56,
        shouldReject: false,
        tags: ["statistics", "regression"],
      },
      {
        id: "protocol-design-fixture",
        title: "Simple research protocol design task",
        task: "Create a protocol workflow that separates question, method, feasibility, execution, and critique.",
        expectedOutputs: ["workflow", "analysis-plan", "qa-report"],
        expectedKeywords: ["protocol", "feasibility", "critique", "artifact", "approval"],
        forbiddenKeywords: ["skip validation"],
        requiredArtifacts: ["workflow", "qa-report"],
        baselineMetric: 0.6,
        shouldReject: false,
        tags: ["protocol"],
      },
      {
        id: "deliberately-flawed-fixture",
        title: "Deliberately flawed candidate rejection case",
        task: "Reject workflows that claim validated research without evaluation artifacts.",
        expectedOutputs: ["workflow", "qa-report"],
        expectedKeywords: ["reject", "evaluation", "artifact"],
        forbiddenKeywords: ["validated without tests", "trust me"],
        requiredArtifacts: ["qa-report"],
        baselineMetric: 0.5,
        shouldReject: true,
        tags: ["adversarial"],
      },
      {
        id: "schema-pass-methods-fail-fixture",
        title: "Schema passes but methodological critique fails",
        task: "Detect a candidate that has JSON-shaped outputs but overclaims unsupported causal inference.",
        expectedOutputs: ["workflow", "analysis-plan", "qa-report"],
        expectedKeywords: ["overclaim", "unsupported", "critique"],
        forbiddenKeywords: ["caused", "proven effective"],
        requiredArtifacts: ["workflow", "analysis-plan", "qa-report"],
        baselineMetric: 0.52,
        shouldReject: true,
        tags: ["methods-critique"],
      },
    ],
    evaluationRubrics: [
      {
        id: "research-methods-rubric",
        title: "Research methods specialization rubric",
        requiredKeywords: ["artifact", "evaluation", "critique"],
        forbiddenKeywords: ["validated without tests", "caused", "trust me"],
        requiredArtifactKinds: ["workflow", "analysis-plan", "qa-report"],
        minScore: 0.74,
        weights: {
          fixtureFit: 0.35,
          artifactCompleteness: 0.25,
          safety: 0.2,
          baselineDelta: 0.2,
        },
      },
    ],
    safetyLimits: {
      maxCostUsd: 0,
      maxRuntimeSeconds: 60,
      maxModelCalls: 0,
      networkAllowed: false,
      cloudAllowed: false,
    },
    persistence: {
      rootDir: path.resolve(rootDir),
      candidatesDir: "candidates",
      evaluationsDir: "evaluations",
      critiquesDir: "critiques",
      repairsDir: "repairs",
      promotionsDir: "promotions",
      artifactsDir: "artifacts",
      reportsDir: "reports",
    },
  };
}
