import type {
  BackendId,
  DatasetAdapterId,
  DatasetAdapterManifest,
  ResearchBackendManifest,
  StudyArchetypeId,
  StudyArchetypeManifest,
} from "./schemas.js";

export const backendCatalog: ResearchBackendManifest[] = [
  {
    schemaVersion: 1,
    id: "duckdb-polars",
    label: "DuckDB/Polars local data preparation",
    role: "data-prep",
    productionStatus: "available",
    supportedModelFamilies: [],
    requiredExecutables: ["python"],
    requiredPackages: ["duckdb", "polars", "pyarrow"],
    inputs: ["CSV", "Parquet", "JSON"],
    outputs: ["cohort-table", "table-summary", "join-plan"],
    limitations: ["Data preparation only; does not produce inferential estimates."],
    verifier: { commandKind: "python-import", required: ["duckdb", "polars", "pyarrow"] },
  },
  {
    schemaVersion: 1,
    id: "python-scipy",
    label: "Python SciPy classical statistics",
    role: "inference",
    productionStatus: "optional",
    supportedModelFamilies: ["hypothesis_test", "correlation", "nonparametric", "power", "multiple_comparison"],
    requiredExecutables: ["python"],
    requiredPackages: ["scipy", "numpy", "pandas"],
    inputs: ["analysis-spec-v2", "cohort-table"],
    outputs: ["test-statistics", "effect-size-summary", "diagnostics"],
    limitations: ["Classical independent-data tests only; complex survey designs need a survey-aware backend."],
    verifier: { commandKind: "python-import", required: ["scipy", "numpy", "pandas"] },
  },
  {
    schemaVersion: 1,
    id: "python-statsmodels",
    label: "Python statsmodels general modeling",
    role: "inference",
    productionStatus: "optional",
    supportedModelFamilies: ["linear", "logistic", "ordinal", "multinomial", "count", "glm", "gee", "time_series", "diagnostics", "epidemiologic", "health_economics", "power"],
    requiredExecutables: ["python"],
    requiredPackages: ["numpy", "pandas", "statsmodels", "pyarrow"],
    inputs: ["analysis-spec-v2", "cohort-table"],
    outputs: ["analysis-json", "model-diagnostics"],
    limitations: ["General regression backend; not the reference engine for complex survey variance."],
    verifier: { commandKind: "python-import", required: ["numpy", "pandas", "statsmodels", "pyarrow"] },
  },
  {
    schemaVersion: 1,
    id: "python-linearized",
    label: "Python local survey-linearized fallback",
    role: "inference",
    productionStatus: "available",
    supportedModelFamilies: ["linear", "logistic"],
    requiredExecutables: ["python"],
    requiredPackages: ["numpy", "pandas", "pyarrow", "statsmodels"],
    inputs: ["analysis-spec-v2", "local-public-health-cache"],
    outputs: ["analysis-json", "paper-md", "runner-record"],
    limitations: ["Fallback implementation; prefer R survey for NHANES/public-health complex survey inference."],
    verifier: { commandKind: "python-import", required: ["numpy", "pandas", "pyarrow", "statsmodels"] },
  },
  {
    schemaVersion: 1,
    id: "r-survey",
    label: "R survey complex-survey inference",
    role: "inference",
    productionStatus: "available",
    supportedModelFamilies: ["descriptive", "hypothesis_test", "linear", "logistic", "prevalence", "epidemiologic", "diagnostics"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["survey", "jsonlite", "arrow"],
    inputs: ["analysis-spec-v2", "cohort-table", "survey-design"],
    outputs: ["analysis-json", "survey-model-summary", "paper-md"],
    limitations: ["Replicate weights, domain estimation, and multi-cycle weight construction must be explicitly modeled before use."],
    verifier: { commandKind: "r-package", required: ["survey", "jsonlite", "arrow"] },
  },
  {
    schemaVersion: 1,
    id: "r-gtsummary",
    label: "R gtsummary reporting",
    role: "table-reporting",
    productionStatus: "optional",
    supportedModelFamilies: ["linear", "logistic", "prevalence"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["gtsummary", "survey", "dplyr", "broom"],
    inputs: ["survey-model-summary", "cohort-table"],
    outputs: ["publication-table", "methods-table"],
    limitations: ["Reporting layer only; depends on validated upstream model output."],
    verifier: { commandKind: "r-package", required: ["gtsummary", "survey", "dplyr", "broom"] },
  },
  {
    schemaVersion: 1,
    id: "r-survival",
    label: "R survival time-to-event modeling",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["survival"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["survival"],
    inputs: ["analysis-spec-v2", "time-to-event-table"],
    outputs: ["survival-summary", "diagnostics", "paper-md"],
    limitations: ["Not enabled until time-origin, censoring, and competing-risk benchmark cases exist."],
    verifier: { commandKind: "r-package", required: ["survival"] },
  },
  {
    schemaVersion: 1,
    id: "r-lme4",
    label: "R mixed-effects modeling",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["mixed_effects", "multilevel"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["lme4"],
    inputs: ["analysis-spec-v2", "clustered-or-longitudinal-table"],
    outputs: ["mixed-model-summary", "convergence-diagnostics"],
    limitations: ["Requires convergence, cluster-count, and random-effects policy benchmarks before execution."],
    verifier: { commandKind: "r-package", required: ["lme4"] },
  },
  {
    schemaVersion: 1,
    id: "r-mice",
    label: "R MICE multiple imputation",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["missing_data"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["mice"],
    inputs: ["analysis-spec-v2", "incomplete-table"],
    outputs: ["imputation-diagnostics", "pooled-estimates"],
    limitations: ["Requires missingness-mechanism review and imputation-model benchmarks before execution."],
    verifier: { commandKind: "r-package", required: ["mice"] },
  },
  {
    schemaVersion: 1,
    id: "r-meta",
    label: "R meta-analysis",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["meta_analysis"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["meta", "metafor"],
    inputs: ["study-level-effects"],
    outputs: ["forest-plot", "heterogeneity-report"],
    limitations: ["Requires study de-duplication and risk-of-bias metadata before execution."],
    verifier: { commandKind: "r-package", required: ["meta", "metafor"] },
  },
  {
    schemaVersion: 1,
    id: "r-lavaan",
    label: "R lavaan latent variable and SEM modeling",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["dimension_reduction", "sem", "reliability"],
    requiredExecutables: ["Rscript"],
    requiredPackages: ["lavaan"],
    inputs: ["analysis-spec-v2", "item-or-path-model"],
    outputs: ["fit-indices", "factor-loadings", "path-summary"],
    limitations: ["Requires identification, measurement-invariance, and fit-index benchmark cases before execution."],
    verifier: { commandKind: "r-package", required: ["lavaan"] },
  },
  {
    schemaVersion: 1,
    id: "python-lifelines",
    label: "Python lifelines survival modeling",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["survival"],
    requiredExecutables: ["python"],
    requiredPackages: ["lifelines", "pandas", "numpy"],
    inputs: ["analysis-spec-v2", "time-to-event-table"],
    outputs: ["survival-summary", "diagnostics"],
    limitations: ["Not enabled until survival benchmark cases prove time-origin and censoring safety."],
    verifier: { commandKind: "python-import", required: ["lifelines", "pandas", "numpy"] },
  },
  {
    schemaVersion: 1,
    id: "python-networkx",
    label: "Python NetworkX graph analysis",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["network"],
    requiredExecutables: ["python"],
    requiredPackages: ["networkx", "pandas"],
    inputs: ["node-table", "edge-table"],
    outputs: ["graph-metrics", "community-report"],
    limitations: ["Requires edge-definition and privacy benchmark cases before execution."],
    verifier: { commandKind: "python-import", required: ["networkx", "pandas"] },
  },
  {
    schemaVersion: 1,
    id: "python-nlp",
    label: "Python NLP/text analysis",
    role: "inference",
    productionStatus: "future",
    supportedModelFamilies: ["nlp", "qualitative", "mixed_methods"],
    requiredExecutables: ["python"],
    requiredPackages: ["sklearn", "pandas", "numpy"],
    inputs: ["text-corpus"],
    outputs: ["text-features", "topic-report", "coding-audit"],
    limitations: ["Requires PHI/PII redaction and human qualitative audit before medical use."],
    verifier: { commandKind: "python-import", required: ["sklearn", "pandas", "numpy"] },
  },
  {
    schemaVersion: 1,
    id: "sklearn",
    label: "Python sklearn prediction modeling",
    role: "ml",
    productionStatus: "future",
    supportedModelFamilies: ["prediction", "dimension_reduction", "clustering", "high_dimensional", "image_signal"],
    requiredExecutables: ["python"],
    requiredPackages: ["sklearn", "numpy", "pandas"],
    inputs: ["feature-matrix", "train-test-split"],
    outputs: ["prediction-metrics", "calibration-report"],
    limitations: ["Not enabled until prediction-model archetype benchmark passes."],
    verifier: { commandKind: "python-import", required: ["sklearn", "numpy", "pandas"] },
  },
  {
    schemaVersion: 1,
    id: "causal",
    label: "Causal inference engine family",
    role: "causal",
    productionStatus: "future",
    supportedModelFamilies: ["propensity_weighting", "mediation", "difference_in_differences", "glm"],
    requiredExecutables: ["python"],
    requiredPackages: [],
    inputs: ["causal-analysis-spec", "identification-assumptions"],
    outputs: ["causal-estimate", "assumption-audit"],
    limitations: ["Requires target-trial or identification review before executable support."],
    verifier: { commandKind: "none", required: [] },
  },
  {
    schemaVersion: 1,
    id: "bayesian",
    label: "Bayesian modeling engine family",
    role: "bayesian",
    productionStatus: "future",
    supportedModelFamilies: ["bayesian", "multilevel", "health_economics"],
    requiredExecutables: ["python"],
    requiredPackages: [],
    inputs: ["bayesian-analysis-spec", "priors"],
    outputs: ["posterior-summary", "diagnostics"],
    limitations: ["Requires prior policy, convergence diagnostics, and compute controls before enablement."],
    verifier: { commandKind: "none", required: [] },
  },
];

export const datasetCatalog: DatasetAdapterManifest[] = [
  {
    schemaVersion: 1,
    id: "nhanes",
    label: "NHANES local/public-cache adapter",
    domain: "public-health-survey",
    productionStatus: "partial",
    localCachePolicy: "required",
    supportedFormats: ["parquet", "csv", "json", "xpt"],
    keyFields: ["SEQN"],
    surveyDesign: {
      supportsWeights: true,
      weightVariables: ["WTINT2YR", "WTMEC2YR", "WTSAF2YR", "WTSAFPRP", "WTMECPRP"],
      strataVariables: ["SDMVSTRA"],
      psuVariables: ["SDMVPSU"],
      replicateWeights: false,
      multiCyclePolicy: "explicit-required",
      weightDomains: [
        {
          weight: "WTINT2YR",
          label: "Interview participants",
          isSubsample: false,
          rationale: "Use the interview survey weight when all variables come from the interview component.",
          eligibilityNote: "interview participants with positive interview weights and complete analysis variables",
          leastCommonDenominatorFor: ["interview questionnaire variables"],
          cycleYears: 2,
          multiCycleConstruction: "Divide each 2-year interview weight by the number of combined 2-year cycles when pooling comparable cycles.",
        },
        {
          weight: "WTMEC2YR",
          label: "MEC exam participants",
          isSubsample: false,
          rationale: "Use the MEC exam survey weight when any analysis variable comes from examination or laboratory components available to MEC participants.",
          eligibilityNote: "MEC-exam participants with positive MEC weights and complete analysis variables",
          leastCommonDenominatorFor: ["examination variables", "standard laboratory variables"],
          cycleYears: 2,
          multiCycleConstruction: "Divide each 2-year MEC weight by the number of combined 2-year cycles when pooling comparable cycles.",
        },
        {
          weight: "WTSAF2YR",
          label: "Morning fasting laboratory subsample",
          isSubsample: true,
          rationale: "Use the fasting subsample survey weight when fasting laboratory measures are required.",
          eligibilityNote: "fasting subsample-eligible participants with positive fasting subsample weights and complete analysis variables",
          leastCommonDenominatorFor: ["fasting glucose", "fasting insulin", "triglycerides when collected in the fasting subsample"],
          cycleYears: 2,
          multiCycleConstruction: "Divide each 2-year fasting subsample weight by the number of combined 2-year cycles when pooling comparable cycles; do not mix with full-sample MEC weights.",
        },
        {
          weight: "WTSAFPRP",
          label: "2017-2020 pre-pandemic fasting laboratory subsample",
          isSubsample: true,
          rationale: "Use the pre-pandemic fasting subsample weight for 2017-2020 pre-pandemic fasting laboratory analyses.",
          eligibilityNote: "2017-2020 pre-pandemic fasting subsample-eligible participants with positive fasting weights and complete analysis variables",
          leastCommonDenominatorFor: ["2017-2020 pre-pandemic fasting laboratory variables"],
          cycleYears: 3.2,
          multiCycleConstruction: "Treat as a special 2017-2020 pre-pandemic weight; do not divide like ordinary 2-year cycles unless a specific CDC-compatible pooling policy is declared.",
        },
        {
          weight: "WTMECPRP",
          label: "2017-2020 pre-pandemic MEC participants",
          isSubsample: false,
          rationale: "Use the pre-pandemic MEC weight for 2017-2020 pre-pandemic MEC analyses.",
          eligibilityNote: "2017-2020 pre-pandemic MEC participants with positive MEC weights and complete analysis variables",
          leastCommonDenominatorFor: ["2017-2020 pre-pandemic examination and standard laboratory variables"],
          cycleYears: 3.2,
          multiCycleConstruction: "Treat as a special 2017-2020 pre-pandemic MEC weight; do not divide like ordinary 2-year cycles unless a specific CDC-compatible pooling policy is declared.",
        },
      ],
    },
    variableMetadata: {
      SEQN: { label: "participant identifier", role: "id", domain: "demographics" },
      SDMVSTRA: { label: "survey strata", role: "survey-design", domain: "demographics" },
      SDMVPSU: { label: "survey primary sampling unit", role: "survey-design", domain: "demographics" },
      WTINT2YR: { label: "interview survey weight", role: "weight", domain: "demographics" },
      WTMEC2YR: { label: "MEC exam survey weight", role: "weight", domain: "demographics" },
      WTSAF2YR: { label: "fasting subsample survey weight", role: "weight", domain: "fasting laboratory" },
      WTSAFPRP: { label: "pre-pandemic fasting subsample survey weight", role: "weight", domain: "fasting laboratory" },
      WTMECPRP: { label: "pre-pandemic MEC survey weight", role: "weight", domain: "demographics" },
      RIDAGEYR: { label: "age", unit: "years", role: "demographic", domain: "demographics" },
      RIAGENDR: { label: "sex", role: "demographic", domain: "demographics" },
      RIDRETH1: { label: "race and ethnicity", role: "demographic", domain: "demographics" },
      INDFMPIR: { label: "family poverty-income ratio", role: "demographic", domain: "demographics" },
      BMXBMI: { label: "body mass index", unit: "kg/m^2", role: "anthropometric", domain: "anthropometrics" },
      BMXWAIST: { label: "waist circumference", unit: "cm", role: "anthropometric", domain: "anthropometrics" },
      LBXGH: { label: "HbA1c", unit: "%", role: "laboratory", domain: "diabetes" },
      LBXGLU: { label: "fasting plasma glucose", unit: "mg/dL", role: "laboratory", domain: "diabetes", caveats: ["Use fasting subsample weights."] },
      LBDHDD: { label: "HDL cholesterol", unit: "mg/dL", role: "laboratory", domain: "lipids" },
      LBXTC: { label: "total cholesterol", unit: "mg/dL", role: "laboratory", domain: "lipids" },
      LBXTR: { label: "triglycerides", unit: "mg/dL", role: "laboratory", domain: "lipids", caveats: ["Often fasting subsample-specific."] },
      LBXVIDMS: { label: "serum 25-hydroxyvitamin D", unit: "nmol/L", role: "laboratory", domain: "vitamin D" },
      BPXSY1: { label: "first systolic blood pressure", unit: "mmHg", role: "clinical-threshold", domain: "blood pressure" },
      BPXDI1: { label: "first diastolic blood pressure", unit: "mmHg", role: "clinical-threshold", domain: "blood pressure" },
      URDACT: { label: "urine albumin-creatinine ratio", unit: "mg/g", role: "laboratory", domain: "kidney" },
    },
    codebookPolicy: "required",
    caveats: [
      "Cross-sectional design limits temporality and causality.",
      "Subsample weights define narrower analytic populations.",
      "Multi-cycle weight construction must be explicit.",
    ],
    validationRules: ["weight-positive", "strata-present", "psu-present", "cycle-policy", "subsample-clearance"],
  },
  {
    schemaVersion: 1,
    id: "brfss",
    label: "BRFSS public survey adapter",
    domain: "public-health-survey",
    productionStatus: "design-only",
    localCachePolicy: "optional",
    supportedFormats: ["csv", "xpt", "parquet"],
    keyFields: [],
    surveyDesign: {
      supportsWeights: true,
      weightVariables: ["_LLCPWT"],
      strataVariables: ["_STSTR"],
      psuVariables: ["_PSU"],
      replicateWeights: false,
      multiCyclePolicy: "explicit-required",
    },
    codebookPolicy: "required",
    caveats: ["Telephone survey with self-report bias and year-specific variable coding."],
    validationRules: ["weight-positive", "codebook-version", "year-policy"],
  },
  {
    schemaVersion: 1,
    id: "seer",
    label: "SEER registry adapter",
    domain: "registry",
    productionStatus: "design-only",
    localCachePolicy: "required",
    supportedFormats: ["csv", "parquet"],
    keyFields: ["patient_id"],
    surveyDesign: { supportsWeights: false, weightVariables: [], strataVariables: [], psuVariables: [], replicateWeights: false, multiCyclePolicy: "not-applicable" },
    codebookPolicy: "required",
    caveats: ["Registry completeness, staging definitions, and release restrictions require explicit metadata."],
    validationRules: ["release-policy", "cell-suppression", "date-consistency"],
  },
  {
    schemaVersion: 1,
    id: "mimic",
    label: "MIMIC-style EHR relational adapter",
    domain: "ehr",
    productionStatus: "partial",
    localCachePolicy: "required",
    supportedFormats: ["csv", "parquet", "duckdb"],
    keyFields: ["subject_id", "hadm_id", "stay_id"],
    surveyDesign: { supportsWeights: false, weightVariables: [], strataVariables: [], psuVariables: [], replicateWeights: false, multiCyclePolicy: "not-applicable" },
    variableMetadata: {
      subject_id: { label: "patient identifier", role: "id", caveats: ["Do not export row-level identifiers."] },
      hadm_id: { label: "hospital admission identifier", role: "id", caveats: ["Use for encounter-level linkage."] },
      stay_id: { label: "ICU stay identifier", role: "id", caveats: ["Use for ICU-level linkage."] },
      hospital_expire_flag: { label: "in-hospital mortality", role: "derived", domain: "outcome", caveats: ["Hospital outcome; not post-discharge mortality."] },
      los_icu: { label: "ICU length of stay", unit: "days", role: "derived", domain: "outcome", caveats: ["Length of stay is affected by care processes and discharge practices."] },
      admission_age: { label: "age at admission", unit: "years", role: "demographic" },
      gender: { label: "recorded sex", role: "demographic" },
      apsiii: { label: "APS III severity score", role: "derived", domain: "severity" },
      oasis: { label: "OASIS severity score", role: "derived", domain: "severity" },
      sofa: { label: "SOFA score", role: "derived", domain: "severity" },
      icd_code: { label: "diagnosis code", role: "derived", domain: "diagnosis" },
      icd_version: { label: "ICD coding system version", role: "derived", domain: "diagnosis" },
      long_title: { label: "diagnosis code description", role: "derived", domain: "diagnosis" },
    },
    codebookPolicy: "required",
    caveats: [
      "Credentialed clinical EHR data; do not export row-level data or identifiers.",
      "Diagnosis-code phenotypes require coding review and sensitivity analyses before publication-quality claims.",
      "Care-process confounding, repeated measures, and timestamp alignment must be explicit.",
      "Simple complete-case ICU outcome models are local-review artifacts, not clinical decision tools.",
    ],
    validationRules: ["temporal-order", "unit-normalization", "encounter-linkage", "diagnosis-code-sensitivity", "row-level-cache-cleanup", "cost-boundary"],
  },
  {
    schemaVersion: 1,
    id: "claims",
    label: "Claims-style longitudinal adapter",
    domain: "claims",
    productionStatus: "design-only",
    localCachePolicy: "required",
    supportedFormats: ["csv", "parquet", "duckdb"],
    keyFields: ["patient_id", "claim_id", "service_date"],
    surveyDesign: { supportsWeights: false, weightVariables: [], strataVariables: [], psuVariables: [], replicateWeights: false, multiCyclePolicy: "not-applicable" },
    codebookPolicy: "required",
    caveats: ["Enrollment continuity, censoring, and coding validity must be checked before inference."],
    validationRules: ["enrollment-continuity", "lookback-window", "followup-window"],
  },
  {
    schemaVersion: 1,
    id: "user-table",
    label: "User-uploaded table adapter",
    domain: "user-upload",
    productionStatus: "partial",
    localCachePolicy: "required",
    supportedFormats: ["csv", "json", "parquet"],
    keyFields: [],
    surveyDesign: { supportsWeights: false, weightVariables: [], strataVariables: [], psuVariables: [], replicateWeights: false, multiCyclePolicy: "not-applicable" },
    codebookPolicy: "recommended",
    caveats: ["Inference quality depends entirely on supplied metadata and validation evidence."],
    validationRules: ["schema-inference", "missingness", "type-stability", "claim-policy"],
  },
  {
    schemaVersion: 1,
    id: "synthetic-fixture",
    label: "Synthetic fixture adapter",
    domain: "synthetic",
    productionStatus: "ready",
    localCachePolicy: "not-applicable",
    supportedFormats: ["json", "csv"],
    keyFields: [],
    surveyDesign: { supportsWeights: false, weightVariables: [], strataVariables: [], psuVariables: [], replicateWeights: false, multiCyclePolicy: "not-applicable" },
    codebookPolicy: "not-applicable",
    caveats: ["Only useful for deterministic tests; never evidence for a real medical claim."],
    validationRules: ["fixture-label", "no-real-claim"],
  },
];

export const archetypeCatalog: StudyArchetypeManifest[] = [
  {
    schemaVersion: 1,
    id: "cross-sectional-association",
    label: "Cross-sectional association",
    questionPatterns: ["associated", "relationship", "linked", "higher", "lower"],
    requiredSpecSections: ["estimand", "population", "variables", "missingness", "model", "claimPolicy"],
    allowedDatasets: ["nhanes", "brfss", "user-table", "synthetic-fixture"],
    allowedBackends: ["r-survey", "python-linearized", "python-statsmodels"],
    modelFamilies: ["linear", "logistic"],
    requiredVariables: ["outcome", "exposure", "covariates", "weights"],
    expectedArtifacts: ["analysis.json", "paper.md", "qa-cli.json", "runner-record.json", "lifecycle.json"],
    qaGates: ["survey-design", "missingness", "claim-safety", "numeric-consistency", "rerun-stability"],
    commonFailureModes: ["missing-variable", "invalid-weight", "high-missingness", "overclaim", "rerun-instability"],
    stopForHumanReviewWhen: ["causal language requested", "unsupported domain analysis", "subsample rationale missing"],
  },
  {
    schemaVersion: 1,
    id: "survey-prevalence",
    label: "Survey-weighted prevalence or threshold estimate",
    questionPatterns: ["prevalence", "proportion", "how common", "threshold"],
    requiredSpecSections: ["estimand", "population", "variables", "surveyDesign", "claimPolicy"],
    allowedDatasets: ["nhanes", "brfss"],
    allowedBackends: ["r-survey", "python-linearized"],
    modelFamilies: ["prevalence", "logistic"],
    requiredVariables: ["outcome", "weights"],
    expectedArtifacts: ["analysis.json", "prevalence-table.json", "paper.md", "qa-cli.json"],
    qaGates: ["threshold-provenance", "survey-design", "small-cell-suppression", "claim-safety"],
    commonFailureModes: ["threshold-without-source", "sparse-cells", "invalid-weight"],
    stopForHumanReviewWhen: ["clinical diagnosis implied from single measurement", "sparse subgroup requested"],
  },
  {
    schemaVersion: 1,
    id: "continuous-biomarker-model",
    label: "Continuous biomarker model",
    questionPatterns: ["biomarker", "level", "mean", "continuous", "laboratory"],
    requiredSpecSections: ["variables", "missingness", "model", "diagnostics"],
    allowedDatasets: ["nhanes", "user-table", "synthetic-fixture"],
    allowedBackends: ["r-survey", "python-linearized", "python-statsmodels"],
    modelFamilies: ["linear"],
    requiredVariables: ["outcome", "exposure", "covariates", "weights"],
    expectedArtifacts: ["analysis.json", "diagnostics.json", "paper.md"],
    qaGates: ["range-plausibility", "missingness", "numeric-consistency", "claim-safety"],
    commonFailureModes: ["implausible-range", "high-missingness", "unit-mismatch"],
    stopForHumanReviewWhen: ["unit conversion ambiguous", "subsample lab weight needed"],
  },
  {
    schemaVersion: 1,
    id: "binary-outcome-model",
    label: "Binary outcome model",
    questionPatterns: ["odds", "binary", "elevated", "yes/no", "risk factor"],
    requiredSpecSections: ["variables", "model.binaryThreshold", "thresholdProvenance", "claimPolicy"],
    allowedDatasets: ["nhanes", "brfss", "user-table", "synthetic-fixture"],
    allowedBackends: ["r-survey", "python-linearized", "python-statsmodels"],
    modelFamilies: ["logistic"],
    requiredVariables: ["outcome", "exposure", "covariates", "weights"],
    expectedArtifacts: ["analysis.json", "paper.md", "qa-cli.json"],
    qaGates: ["threshold-provenance", "odds-ratio-consistency", "sparse-cells", "claim-safety"],
    commonFailureModes: ["missing-threshold", "separation", "sparse-cells"],
    stopForHumanReviewWhen: ["threshold is clinical diagnostic criterion", "rare endpoint"],
  },
  {
    schemaVersion: 1,
    id: "ehr-diagnosis-cohort-outcome",
    label: "EHR diagnosis-code cohort outcome model",
    questionPatterns: ["diagnosis code", "ICD", "ICU outcome", "mortality", "length of stay", "hospital outcome"],
    requiredSpecSections: ["datasetAccess", "phenotype", "population", "variables", "model", "claimPolicy", "failurePolicy"],
    allowedDatasets: ["mimic", "claims", "user-table", "synthetic-fixture"],
    allowedBackends: ["python-statsmodels"],
    modelFamilies: ["logistic", "linear", "epidemiologic"],
    requiredVariables: ["outcome", "exposure", "covariates"],
    expectedArtifacts: ["dataset-run.json", "analysis-results.json", "paper.md", "qa.json", "matched-icd-codes.csv", "run-manifest.json", "cost-receipt.json", "lifecycle.json"],
    qaGates: ["diagnosis-code-verification", "cohort-nonempty", "sparse-events", "events-per-predictor", "nonfinite-effects", "cache-cleanup", "cost-ceiling"],
    commonFailureModes: ["missing-table", "missing-diagnosis-code", "small-cohort", "sparse-outcome", "nonfinite-effect", "cost-ceiling", "cache-left-behind"],
    stopForHumanReviewWhen: ["phenotype lacks coding review", "events per predictor below threshold", "causal language requested", "row-level data would be exported"],
  },
  {
    schemaVersion: 1,
    id: "subgroup-domain-analysis",
    label: "Subgroup/domain analysis",
    questionPatterns: ["by subgroup", "effect modification", "interaction", "domain", "stratified"],
    requiredSpecSections: ["stratifiers", "surveyDesign", "smallCellPolicy", "interactionModel"],
    allowedDatasets: ["nhanes", "brfss"],
    allowedBackends: ["r-survey"],
    modelFamilies: ["linear", "logistic", "prevalence"],
    requiredVariables: ["outcome", "exposure", "covariates", "weights"],
    expectedArtifacts: ["domain-table.json", "suppression-report.json", "paper.md"],
    qaGates: ["domain-variance", "small-cell-suppression", "interaction-claim-safety"],
    commonFailureModes: ["unsupported-domain-semantics", "sparse-cells", "multiple-comparison-overclaim"],
    stopForHumanReviewWhen: ["domain variance not implemented", "subgroup cell count below policy"],
  },
  {
    schemaVersion: 1,
    id: "subsample-high-missingness",
    label: "Subsample or high-missingness analysis",
    questionPatterns: ["fasting", "subsample", "missing", "laboratory subsample"],
    requiredSpecSections: ["surveyDesign.weightRationale", "eligibilityNote", "missingness"],
    allowedDatasets: ["nhanes"],
    allowedBackends: ["r-survey", "python-linearized"],
    modelFamilies: ["linear", "logistic"],
    requiredVariables: ["outcome", "exposure", "covariates", "weights"],
    expectedArtifacts: ["weight-domain.json", "missingness.json", "paper.md", "qa-cli.json"],
    qaGates: ["subsample-clearance", "missingness", "claim-safety", "rerun-stability"],
    commonFailureModes: ["missing-weight-rationale", "eligibility-unclear", "high-missingness"],
    stopForHumanReviewWhen: ["subsample eligibility cannot be proven", "missingness exceeds threshold"],
  },
  {
    schemaVersion: 1,
    id: "diagnostic-accuracy",
    label: "Diagnostic accuracy study",
    questionPatterns: ["sensitivity", "specificity", "diagnostic", "screening", "accuracy"],
    requiredSpecSections: ["indexTest", "goldStandard", "thresholds", "spectrumBias"],
    allowedDatasets: ["user-table", "mimic", "synthetic-fixture"],
    allowedBackends: ["python-statsmodels"],
    modelFamilies: ["diagnostic_accuracy"],
    requiredVariables: ["outcome", "exposure", "goldStandard"],
    expectedArtifacts: ["confusion-matrix.json", "diagnostic-metrics.json", "paper.md"],
    qaGates: ["gold-standard", "threshold-provenance", "spectrum-bias", "claim-safety"],
    commonFailureModes: ["no-gold-standard", "threshold-overfit", "spectrum-bias"],
    stopForHumanReviewWhen: ["reference standard is imperfect", "screening recommendation implied"],
  },
  {
    schemaVersion: 1,
    id: "prediction-model",
    label: "Prediction model",
    questionPatterns: ["predict", "forecast", "risk score", "classification"],
    requiredSpecSections: ["target", "features", "splitPolicy", "calibration", "fairness"],
    allowedDatasets: ["user-table", "mimic", "claims", "synthetic-fixture"],
    allowedBackends: ["sklearn"],
    modelFamilies: ["prediction"],
    requiredVariables: ["outcome", "covariates"],
    expectedArtifacts: ["model-card.json", "metrics.json", "calibration.json", "paper.md"],
    qaGates: ["split-leakage", "calibration", "external-validation-plan", "claim-safety"],
    commonFailureModes: ["data-leakage", "overfitting", "poor-calibration"],
    stopForHumanReviewWhen: ["clinical deployment implied", "no validation split"],
  },
  {
    schemaVersion: 1,
    id: "target-trial-emulation-sketch",
    label: "Target trial emulation sketch",
    questionPatterns: ["effect of", "causal", "treatment", "intervention"],
    requiredSpecSections: ["eligibilityTimeZero", "treatmentStrategies", "assignmentProcedure", "followup", "estimand"],
    allowedDatasets: ["mimic", "claims", "user-table"],
    allowedBackends: ["causal"],
    modelFamilies: ["propensity_weighting"],
    requiredVariables: ["outcome", "exposure", "covariates", "time"],
    expectedArtifacts: ["target-trial-protocol.json", "assumption-audit.json"],
    qaGates: ["time-zero", "positivity", "exchangeability", "causal-claim-review"],
    commonFailureModes: ["immortal-time-bias", "confounding-by-indication", "positivity-violation"],
    stopForHumanReviewWhen: ["any causal claim before protocol review"],
  },
  {
    schemaVersion: 1,
    id: "interrupted-time-series",
    label: "Interrupted time series",
    questionPatterns: ["policy change", "interrupted", "before and after", "time series"],
    requiredSpecSections: ["timeIndex", "interventionDate", "autocorrelationPolicy", "seasonality"],
    allowedDatasets: ["claims", "user-table"],
    allowedBackends: ["python-statsmodels"],
    modelFamilies: ["time_series"],
    requiredVariables: ["outcome", "time"],
    expectedArtifacts: ["time-series-diagnostics.json", "counterfactual-plot.png", "paper.md"],
    qaGates: ["autocorrelation", "seasonality", "pretrend", "claim-safety"],
    commonFailureModes: ["insufficient-pre-period", "unmodeled-seasonality", "cointervention"],
    stopForHumanReviewWhen: ["policy conclusion requested"],
  },
  {
    schemaVersion: 1,
    id: "difference-in-differences",
    label: "Difference-in-differences",
    questionPatterns: ["difference in differences", "treated vs control", "policy effect"],
    requiredSpecSections: ["treatmentGroup", "comparisonGroup", "prePostPeriods", "parallelTrends"],
    allowedDatasets: ["claims", "user-table"],
    allowedBackends: ["causal"],
    modelFamilies: ["difference_in_differences"],
    requiredVariables: ["outcome", "exposure", "time", "covariates"],
    expectedArtifacts: ["parallel-trends.json", "event-study.json", "paper.md"],
    qaGates: ["parallel-trends", "spillover", "group-comparability", "causal-claim-review"],
    commonFailureModes: ["parallel-trends-violation", "spillover", "composition-change"],
    stopForHumanReviewWhen: ["parallel trends not shown", "causal policy claim requested"],
  },
];

export function getBackendManifest(id: BackendId): ResearchBackendManifest {
  const manifest = backendCatalog.find(item => item.id === id);
  if (!manifest) throw new Error(`Unknown backend: ${id}`);
  return manifest;
}

export function getDatasetManifest(id: DatasetAdapterId): DatasetAdapterManifest {
  const manifest = datasetCatalog.find(item => item.id === id);
  if (!manifest) throw new Error(`Unknown dataset adapter: ${id}`);
  return manifest;
}

export function getArchetypeManifest(id: StudyArchetypeId): StudyArchetypeManifest {
  const manifest = archetypeCatalog.find(item => item.id === id);
  if (!manifest) throw new Error(`Unknown study archetype: ${id}`);
  return manifest;
}
